
[build.environment]
  NPM_VERSION = "7.9.0"
  NODE_VERSION = "15.0.1"

[build]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[context.production]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[context.deploy-preview]
  publish = "api-docs/_build/html"
  command = "cd api-docs && make clean html && cd .."

[[redirects]]
  from = "/*"
  to = "/docs/cloud-orchestration/v1/:splat"
  status = 301
  force = false