
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "api-docs/_build/dirhtml"
  command = "cd api-docs && make clean dirhtml && cd .."

[context.production]
  publish = "api-docs/_build/dirhtml"
  command = "cd api-docs && make clean dirhtml && cd .."

[context.deploy-preview]
  publish = "api-docs/_build/dirhtml"
  command = "cd api-docs && make clean dirhtml && cd .."
